### ISSUE TITLE
Line 59 of fit_clusters.R

### ISSUE THREAD

**Issue by anjalisilva** [ecsg-uoy/DLBCLGenomicSubtyping#1]
Thank you for this work. I believe line 59 of fit_clusters.R should be altered. 
```
muts_all$ClusterICL <- as.factor(paste0('C', bic@cluster))
```
While this line may work for the example you have provided, as BIC/ICL have both resulted a 4 cluster model, this may not work for other cases. 

As BIC and ICL penalizations differ, the models they select can sometimes differ. So below lines should work better.
```
muts_all$ClusterBIC <- as.factor(paste0('C', bic@cluster))
muts_all$ClusterICL <- as.factor(paste0('C', icl@cluster))
```

**Comment by stulacy** [comment]
That's a good point! I no longer maintain this repository as I'm in a different group now, but I've submitted a PR (#2 ) that makes this ICL/BIC distinction explicit.

**Comment by anjalisilva** [comment]
Thank you, Stuart!
